batch_size: 8
lr: 1.0e-6
batch_norm: False
basic_model: vgg16
#save_dir: ckpt/attr
save_dir: ckpt/attr1000
path_base: /home/arcthing/qiaohan/data/cloth_data/DeepFashion/
datalist_file: datalist/attr_pos_neg.txt
#datalist_file: datalist/attrsam.txt
save_period: 1000
num_epochs: 5
#image format
channels: 3
bgr: False
crop_shape:
  w: 225
  h: 300
scale_shape:
  w: 224
  h: 224
